### ISSUE TITLE
One more credential error.

### ISSUE THREAD

**Issue by r4sk01** [IBM/cos-web-gallery#15]
I am getting an error while uploading the image "Missing credentials in config".

May you please explain that step: 
Paste the contents into a file named `~/.bluemix/cos_credentials`.

First of all I do not have that file, so I create it. 
Is it .txt .js ? 
What should I put in it, node.js string like 
{
"api-key":"XXXX", 
....}

I just copied credentials and put it and got a mistake I mentioned before.

**Comment by loafyloaf** [comment]
Hello again @r4sk01 - please reopen this issue if you are still having problems...

**Comment by r4sk01** [comment]
Hi @loafyloaf , sorry for a late reply. It took some time to test it, I confirm it works now. I did not really change anything, just did all the order from the scratch. Thank you for help!

**Comment by kklepper** [comment]
I did as you described, but still...

I installed into `D:\www\cos-web-gallery`, so the file `.bluemix/cos_credentials` resides there, the content of which is taken from the clipboard. Is that location correct?


D:\www\cos-web-gallery>npm start

```
> cos-web-gallery@0.0.2 start D:\www\cos-web-gallery
> node app.js

To view your app, open this link in your browser: http://localhost:3000
```
That address works. Using the browser, I tried to upload a file, resulting in:

```{
  fieldname: 'img-file',
  originalname: 'P1000589.JPG',
  encoding: '7bit',
  mimetype: 'image/jpeg'
}
CredentialsError: Missing credentials in config
    at Object.openSync (fs.js:458:3)
    at Object.readFileSync (fs.js:360:35)
    at Object.readFileSync (D:\www\cos-web-gallery\node_modules\ibm-cos-sdk\lib\util.js:96:26)
    at SharedIniFileCredentials.refresh (D:\www\cos-web-gallery\node_modules\ibm-cos-sdk\lib\credentials\shared_ini_file_credentials.js:73:47)
    at SharedIniFileCredentials.get (D:\www\cos-web-gallery\node_modules\ibm-cos-sdk\lib\credentials.js:140:18)
    at resolveNext (D:\www\cos-web-gallery\node_modules\ibm-cos-sdk\lib\credentials\credential_provider_chain.js:119:15)
    at D:\www\cos-web-gallery\node_modules\ibm-cos-sdk\lib\credentials\credential_provider_chain.js:120:11
    at D:\www\cos-web-gallery\node_modules\ibm-cos-sdk\lib\credentials.js:142:31
    at SharedJSONFileCredentials.refresh (D:\www\cos-web-gallery\node_modules\ibm-cos-sdk\lib\credentials\shared_json_file_credentials.js:90:13)
    at SharedJSONFileCredentials.get (D:\www\cos-web-gallery\node_modules\ibm-cos-sdk\lib\credentials.js:140:18)

```

What am I doing wrong? 

My `galleryController.js` reads like this:

```
    var ep = new aws.Endpoint('https://s3.private.fra.eu.cloud-object-storage.appdomain.cloud');
    var s3 = new aws.S3({endpoint: ep, region: 'eu-geo'});
    var myBucket = 'k48k-mybucketname-1';

```

Using `https://cloud.ibm.com/objectstorage/...`, I could upload files to this bucket without problem.
